/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.mjaroslav.vkgallery;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class VKGalleryTest {
    @Test void appHasAGreeting() {
        var classUnderTest = new VKGallery();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
