/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.mjaroslav.vkgallery;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import lombok.val;
import org.jetbrains.annotations.NotNull;

public class VKGallery extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(@NotNull Stage primaryStage) throws Exception {
        val root = new VBox();
        val scene = new Scene(root, 300, 300);
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
