/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.mjaroslav.vkgallery;

import io.github.mjaroslav.vkgallery.util.FXMLUtils;
import io.github.mjaroslav.vkgallery.vk.VKHelper;
import javafx.application.Application;
import javafx.stage.Stage;
import lombok.val;
import org.jetbrains.annotations.NotNull;

public class VKGallery extends Application {
    public static final VKHelper VK = new VKHelper();
    public static Stage PRIMARY_STAGE;

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(@NotNull Stage primaryStage) throws Exception {
        PRIMARY_STAGE = primaryStage;
        VK.login(primaryStage);
        primaryStage.setResizable(true);
        primaryStage.setMinWidth(600);
        primaryStage.setMinHeight(400);
//        FXMLUtils.changeScene(primaryStage, "Main");
        primaryStage.show();
    }
}
